/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package app.kafka.schemaapp.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BaselineEventStructure extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5413464511972960782L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"BaselineEventStructure\",\"namespace\":\"app.kafka.schemaapp.schema\",\"fields\":[{\"name\":\"header\",\"type\":{\"type\":\"record\",\"name\":\"MessageHeader\",\"fields\":[{\"name\":\"eventName\",\"type\":{\"type\":\"enum\",\"name\":\"EventName\",\"symbols\":[\"CreateEnrolmentEvent\",\"CancelEnrolmentEvent\"]}}]}},{\"name\":\"payload\",\"type\":[{\"type\":\"record\",\"name\":\"CreateEnrolment\",\"fields\":[{\"name\":\"entityId\",\"type\":\"int\"},{\"name\":\"rewardName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"rewardMembershipId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]},{\"type\":\"record\",\"name\":\"CancelEnrolment\",\"fields\":[{\"name\":\"entityId\",\"type\":\"int\"},{\"name\":\"rewardName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"reasonCode\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"ReasonCode\",\"symbols\":[\"MemberRequested\",\"PolicyCancelled\",\"PartnerMembershipCancelled\"]}]}]}]}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BaselineEventStructure> ENCODER = new BinaryMessageEncoder<BaselineEventStructure>(
      MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BaselineEventStructure> DECODER = new BinaryMessageDecoder<BaselineEventStructure>(
      MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * 
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BaselineEventStructure> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * 
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BaselineEventStructure> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the
   * specified {@link SchemaStore}.
   * 
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given
   *         SchemaStore
   */
  public static BinaryMessageDecoder<BaselineEventStructure> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BaselineEventStructure>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BaselineEventStructure to a ByteBuffer.
   * 
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BaselineEventStructure from a ByteBuffer.
   * 
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BaselineEventStructure instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into
   *                             an instance of this class
   */
  public static BaselineEventStructure fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private app.kafka.schemaapp.schema.MessageHeader header;
  private java.lang.Object payload;

  /**
   * Default constructor. Note that this does not initialize fields
   * to their default values from the schema. If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BaselineEventStructure() {
  }

  /**
   * All-args constructor.
   * 
   * @param header  The new value for header
   * @param payload The new value for payload
   */
  public BaselineEventStructure(app.kafka.schemaapp.schema.MessageHeader header, java.lang.Object payload) {
    this.header = header;
    this.payload = payload;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter. Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return header;
      case 1:
        return payload;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader. Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        header = (app.kafka.schemaapp.schema.MessageHeader) value$;
        break;
      case 1:
        payload = value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'header' field.
   * 
   * @return The value of the 'header' field.
   */
  public app.kafka.schemaapp.schema.MessageHeader getHeader() {
    return header;
  }

  /**
   * Sets the value of the 'header' field.
   * 
   * @param value the value to set.
   */
  public void setHeader(app.kafka.schemaapp.schema.MessageHeader value) {
    this.header = value;
  }

  /**
   * Gets the value of the 'payload' field.
   * 
   * @return The value of the 'payload' field.
   */
  public java.lang.Object getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * 
   * @param value the value to set.
   */
  public void setPayload(java.lang.Object value) {
    this.payload = value;
  }

  /**
   * Creates a new BaselineEventStructure RecordBuilder.
   * 
   * @return A new BaselineEventStructure RecordBuilder
   */
  public static app.kafka.schemaapp.schema.BaselineEventStructure.Builder newBuilder() {
    return new app.kafka.schemaapp.schema.BaselineEventStructure.Builder();
  }

  /**
   * Creates a new BaselineEventStructure RecordBuilder by copying an existing
   * Builder.
   * 
   * @param other The existing builder to copy.
   * @return A new BaselineEventStructure RecordBuilder
   */
  public static app.kafka.schemaapp.schema.BaselineEventStructure.Builder newBuilder(
      app.kafka.schemaapp.schema.BaselineEventStructure.Builder other) {
    if (other == null) {
      return new app.kafka.schemaapp.schema.BaselineEventStructure.Builder();
    } else {
      return new app.kafka.schemaapp.schema.BaselineEventStructure.Builder(other);
    }
  }

  /**
   * Creates a new BaselineEventStructure RecordBuilder by copying an existing
   * BaselineEventStructure instance.
   * 
   * @param other The existing instance to copy.
   * @return A new BaselineEventStructure RecordBuilder
   */
  public static app.kafka.schemaapp.schema.BaselineEventStructure.Builder newBuilder(
      app.kafka.schemaapp.schema.BaselineEventStructure other) {
    if (other == null) {
      return new app.kafka.schemaapp.schema.BaselineEventStructure.Builder();
    } else {
      return new app.kafka.schemaapp.schema.BaselineEventStructure.Builder(other);
    }
  }

  /**
   * RecordBuilder for BaselineEventStructure instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BaselineEventStructure>
      implements org.apache.avro.data.RecordBuilder<BaselineEventStructure> {

    private app.kafka.schemaapp.schema.MessageHeader header;
    private app.kafka.schemaapp.schema.MessageHeader.Builder headerBuilder;
    private java.lang.Object payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * 
     * @param other The existing Builder to copy.
     */
    private Builder(app.kafka.schemaapp.schema.BaselineEventStructure.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasHeaderBuilder()) {
        this.headerBuilder = app.kafka.schemaapp.schema.MessageHeader.newBuilder(other.getHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.payload)) {
        this.payload = data().deepCopy(fields()[1].schema(), other.payload);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing BaselineEventStructure instance
     * 
     * @param other The existing instance to copy.
     */
    private Builder(app.kafka.schemaapp.schema.BaselineEventStructure other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      this.headerBuilder = null;
      if (isValidValue(fields()[1], other.payload)) {
        this.payload = data().deepCopy(fields()[1].schema(), other.payload);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'header' field.
     * 
     * @return The value.
     */
    public app.kafka.schemaapp.schema.MessageHeader getHeader() {
      return header;
    }

    /**
     * Sets the value of the 'header' field.
     * 
     * @param value The value of 'header'.
     * @return This builder.
     */
    public app.kafka.schemaapp.schema.BaselineEventStructure.Builder setHeader(
        app.kafka.schemaapp.schema.MessageHeader value) {
      validate(fields()[0], value);
      this.headerBuilder = null;
      this.header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'header' field has been set.
     * 
     * @return True if the 'header' field has been set, false otherwise.
     */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'header' field and creates one if it
     * doesn't exist yet.
     * 
     * @return This builder.
     */
    public app.kafka.schemaapp.schema.MessageHeader.Builder getHeaderBuilder() {
      if (headerBuilder == null) {
        if (hasHeader()) {
          setHeaderBuilder(app.kafka.schemaapp.schema.MessageHeader.newBuilder(header));
        } else {
          setHeaderBuilder(app.kafka.schemaapp.schema.MessageHeader.newBuilder());
        }
      }
      return headerBuilder;
    }

    /**
     * Sets the Builder instance for the 'header' field
     * 
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public app.kafka.schemaapp.schema.BaselineEventStructure.Builder setHeaderBuilder(
        app.kafka.schemaapp.schema.MessageHeader.Builder value) {
      clearHeader();
      headerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'header' field has an active Builder instance
     * 
     * @return True if the 'header' field has an active Builder instance
     */
    public boolean hasHeaderBuilder() {
      return headerBuilder != null;
    }

    /**
     * Clears the value of the 'header' field.
     * 
     * @return This builder.
     */
    public app.kafka.schemaapp.schema.BaselineEventStructure.Builder clearHeader() {
      header = null;
      headerBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'payload' field.
     * 
     * @return The value.
     */
    public java.lang.Object getPayload() {
      return payload;
    }

    /**
     * Sets the value of the 'payload' field.
     * 
     * @param value The value of 'payload'.
     * @return This builder.
     */
    public app.kafka.schemaapp.schema.BaselineEventStructure.Builder setPayload(java.lang.Object value) {
      validate(fields()[1], value);
      this.payload = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'payload' field has been set.
     * 
     * @return True if the 'payload' field has been set, false otherwise.
     */
    public boolean hasPayload() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'payload' field.
     * 
     * @return This builder.
     */
    public app.kafka.schemaapp.schema.BaselineEventStructure.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BaselineEventStructure build() {
      try {
        BaselineEventStructure record = new BaselineEventStructure();
        if (headerBuilder != null) {
          try {
            record.header = this.headerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("header"));
            throw e;
          }
        } else {
          record.header = fieldSetFlags()[0] ? this.header
              : (app.kafka.schemaapp.schema.MessageHeader) defaultValue(fields()[0]);
        }
        record.payload = fieldSetFlags()[1] ? this.payload : defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BaselineEventStructure> WRITER$ = (org.apache.avro.io.DatumWriter<BaselineEventStructure>) MODEL$
      .createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BaselineEventStructure> READER$ = (org.apache.avro.io.DatumReader<BaselineEventStructure>) MODEL$
      .createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
