/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package app.kafka.avrodemo.schema;
@org.apache.avro.specific.AvroGenerated
public enum Reason implements org.apache.avro.generic.GenericEnumSymbol<Reason> {
  NotUsed, EnrolledElseWhere, TooExpensive, PoorCustomerService  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Reason\",\"namespace\":\"app.kafka.avrodemo.schema\",\"symbols\":[\"NotUsed\",\"EnrolledElseWhere\",\"TooExpensive\",\"PoorCustomerService\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
